services:
  - type: web
    name: smart-warehouse-api
    env: python
    runtime: python-3.11.6
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
